/**
 * Share previews for a product link.
 *
 * ── The problem this solves ────────────────────────────────────────────────
 * The storefront is one page. A product link was `/?p=<id>`, and a query string
 * changes nothing a scraper can see: WhatsApp, Facebook and X fetch the URL,
 * read the Open Graph tags out of the HTML, and never run the JavaScript that
 * would swap in the product. So every product ever shared previewed with the
 * site-wide title, description and banner — the same card for a betta and a
 * filter, showing neither.
 *
 * Static per-product pages (`/p/<slug>`) exist for search engines, but they are
 * generated by hand from `seo/generate.mjs` and only cover products that were
 * listed the last time someone ran it. A product listed this morning has no
 * page, and a share link that 404s is worse than a generic preview.
 *
 * ── How it works ───────────────────────────────────────────────────────────
 * This renders the tags per product, at request time, from the live database.
 * The catalogue is world-readable (see database.rules.json) and product images
 * are public in Storage, so no credentials are involved and nothing here can
 * read anything a shopper could not.
 *
 * A scraper gets the tags and stops. A human gets redirected into the app at
 * `/?p=<id>`, which is where the link always went. The redirect is JavaScript
 * plus a `<noscript>` refresh rather than a 302, because a 302 would send the
 * scraper to the storefront and it would read the site-wide tags again —
 * exactly the bug being fixed.
 */

const DB = 'https://nemo-aqua-store-default-rtdb.asia-southeast1.firebasedatabase.app';
const SITE = 'https://www.nemoaquastore.in';
const STORE = 'Nemo Aqua Store';
const FALLBACK_IMAGE = `${SITE}/assets/share-banner.jpg`;

const esc = (v) =>
  String(v == null ? '' : v).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]
  );

/** The picture the card should show: the product's first real photo. */
function imageOf(product) {
  const media = Array.isArray(product && product.media) ? product.media : [];
  for (const m of media) {
    if (!m || m.type === 'video') continue;
    // Full image first — a thumbnail upscaled into a 1200x630 card looks soft.
    if (m.url) return m.url;
    if (m.thumbUrl) return m.thumbUrl;
  }
  return FALLBACK_IMAGE;
}

/** Selling price, matching the storefront's own discount rule. */
function priceOf(product) {
  const base = Number(product && product.price) || 0;
  const pct = Number(product && product.discountPct) || 0;
  const ends = product && product.offerEndsAt ? new Date(product.offerEndsAt).getTime() : NaN;
  const live = pct > 0 && (isNaN(ends) || ends > Date.now());
  return live ? Math.round(base * (1 - pct / 100)) : base;
}

export default async function handler(req, res) {
  const id = String((req.query && req.query.id) || '').trim();
  const target = id ? `${SITE}/?p=${encodeURIComponent(id)}` : SITE;

  let product = null;
  if (/^[A-Za-z0-9_-]{1,64}$/.test(id)) {
    try {
      const r = await fetch(`${DB}/products/${encodeURIComponent(id)}.json`, {
        signal: AbortSignal.timeout(4000),
      });
      if (r.ok) product = await r.json();
    } catch (e) {
      // A slow or unreachable database must not make the link dead. Falling
      // through renders the site-level card, which is what used to happen
      // always — a worse preview, still a working link.
    }
  }

  const title = product && product.name ? `${product.name} — ₹${priceOf(product)}` : STORE;
  const description =
    product && product.desc
      ? String(product.desc).replace(/\s+/g, ' ').trim().slice(0, 160)
      : 'Hand-picked healthy fish, live plants & quality accessories — delivered with care across India.';
  const image = product ? imageOf(product) : FALLBACK_IMAGE;
  const url = `${SITE}/s/${encodeURIComponent(id)}`;

  // Scrapers re-fetch a link every time it is shared; five minutes keeps that
  // cheap while a re-priced product still corrects itself quickly.
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'public, s-maxage=300, stale-while-revalidate=3600');
  // This page is a redirect shim, never a search result — the indexable copy is
  // the storefront itself.
  res.setHeader('X-Robots-Tag', 'noindex');

  res.status(200).send(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}"/>
<meta name="robots" content="noindex,follow"/>

<meta property="og:type" content="product"/>
<meta property="og:site_name" content="${esc(STORE)}"/>
<meta property="og:title" content="${esc(title)}"/>
<meta property="og:description" content="${esc(description)}"/>
<meta property="og:url" content="${esc(url)}"/>
<meta property="og:image" content="${esc(image)}"/>
<meta property="og:image:alt" content="${esc(product && product.name ? product.name : STORE)}"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="${esc(title)}"/>
<meta name="twitter:description" content="${esc(description)}"/>
<meta name="twitter:image" content="${esc(image)}"/>

<link rel="canonical" href="${esc(target)}"/>
<noscript><meta http-equiv="refresh" content="0;url=${esc(target)}"/></noscript>
<script>location.replace(${JSON.stringify(target)});</script>
</head>
<body style="font:15px/1.5 system-ui,sans-serif;padding:24px;color:#132740">
<p>Opening ${esc(product && product.name ? product.name : STORE)}…</p>
<p><a href="${esc(target)}">Continue to ${esc(STORE)}</a></p>
</body>
</html>`);
}
